# Generated by Django 4.0.6 on 2022-08-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Bug'), ('Developer', 'Developer'), ('Submitter', 'Submitter')], default='Developer', max_length=10),
        ),
    ]
