# Generated by Django 4.0.6 on 2022-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Submitter', 'Submitter')], default='Developer', max_length=10),
        ),
    ]
