# Generated by Django 4.0.6 on 2022-07-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
