# Generated by Django 4.0.6 on 2022-07-16 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_project_mem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mem',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dev',
        ),
    ]
