# Generated by Django 4.0.6 on 2022-07-16 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_project_mem_project_members_delete_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(null=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
