# Generated by Django 4.0.6 on 2022-07-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dev',
        ),
    ]
