# Generated by Django 4.0.6 on 2022-07-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
