# Generated by Django 4.0.6 on 2022-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
