# Generated by Django 4.0.6 on 2022-07-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_comment_commenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('B', 'Bug'), ('F', 'Feature Request'), ('O', 'Other')], default='B', max_length=1),
        ),
    ]
