# Generated by Django 4.0.6 on 2022-07-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('B', 'Bug'), ('F', 'Feature Request'), ('O', 'Other')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('I', 'In Progress'), ('R', 'Resolved'), ('A', 'Additional Info Required')], default='I', max_length=1),
        ),
    ]
