# Generated by Django 4.0.6 on 2022-07-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_bug_priority_bug_type_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug', to=settings.AUTH_USER_MODEL),
        ),
    ]
