# Generated by Django 4.0.6 on 2022-07-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
