# Generated by Django 4.0.6 on 2022-07-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_bug_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='api.member'),
        ),
    ]
