# Generated by Django 4.0.6 on 2022-07-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_bug_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
