# Generated by Django 4.0.6 on 2022-07-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_bug_profile_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=7),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Additional Info Required', 'Additional Info Required')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('Other', 'Other')], default='Bug', max_length=16),
        ),
    ]
