# Generated by Django 4.0.6 on 2022-07-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_bug_priority_alter_bug_status_alter_bug_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.bug'),
        ),
    ]
